---
title: "Class 3: Introduction to Causal Inference"
---

Today we'll introduce the potential outcomes framework. We'll discuss what this means and what we'll seek to estimate going forward.

## Objectives
- Explain potential outcomes
- Derive and explain the average treatment effect 
- Explain the differences between an average treatment effect and the average treatment effect on the treated

## Activities
- Finalize software setup
- Confirm ability to commit and push changes to GitHub
- Create your own [Medicare Advantage repository](https://github.com/imccart/ma-class) and begin working with data. Some specific steps...
    1. Create an SSH key on your computer and pair with GitHub
    2. Create GitHub repository
    3. Clone to your local computer
    4. Create folder structure (check [Assignments Page](/assignment/) for more detail)
    5. Download data from OneDrive (check link on Canvas) and move to `data/input` folder
    6. Download code from the GitHub repository for the assignment and move to `data-code` folder
